export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_MENU_URL="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=25.4358011&lng=81.846311&restaurantId=";

export const restrauntList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "147619",
        name: "Jai Shree Shankar Punjabi Dhaba",
        uuid: "11c317e4-da0e-48b7-88db-0856a9790f31",
        city: "50",
        area: "Civil Lines",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "y5di27ne45qwv0xiklzd",
        cuisines: [
          "Indian",
          "North Indian",
          "Chinese",
          "South Indian",
          "Snacks",
          "Punjabi",
          "Beverages",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "jai-shree-shankar-punjabi-dhaba-civil-lines-civil-lines",
          city: "allahabad",
        },
        cityState: "50",
        address: "29/61, M.G.Road, Civil Lines, Allahabad",
        locality: "Mahatma Gandhi Marg",
        parentId: 108723,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2300,
          message: "",
          title: "Delivery Charge",
          amount: "2300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7420183~p=7~eid=00000189-39f8-0aa0-0b6e-f7ff0033077a~srvts=1688894704288",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "147619",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.6",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    // 1st
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "80321",
        name: "Paradise Confectioner",
        uuid: "e5de83c6-bfd1-4176-b520-1e75adeca747",
        city: "50",
        area: "Tagore Town",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "a7luxwotbrfgjpzdewyk",
        cuisines: ["Bakery", "Desserts", "Pizzas", "Burgers", "Snacks"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "paradise-confectioner-tagore-town-civil-lines",
          city: "allahabad",
        },
        cityState: "50",
        address: "3/3 Hashimpur Road, Tagore Town, Allahabad",
        locality: "Hashimpur Road",
        parentId: 155099,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7270352~p=1~eid=00000189-3539-747c-07ff-165e00720117~srvts=1688815105148",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹900",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "80321",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
  
    // 2nd
  
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "224920",
        name: "Chandralok Kachouri",
        uuid: "08c5f3d4-4e02-4829-aac1-a47ca48dce73",
        city: "50",
        area: "Rambagh",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "qbo11lh7l43xpkd7wqts",
        cuisines: ["Snacks", "South Indian", "Chinese", "Fast Food", "Pizzas"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 16,
        minDeliveryTime: 16,
        maxDeliveryTime: 16,
        slaString: "16 MINS",
        lastMileTravel: 0.30000001192092896,
        slugs: {
          restaurant: "chandralok-kachouri-chowk-chowk",
          city: "allahabad",
        },
        cityState: "50",
        address:
          "K.P. Kakkar Road, In Front of Chandralok Cinema, Chowk, Allahabad",
        locality: "Kp Kakkar Road",
        parentId: 57887,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1400,
          message: "",
          title: "Delivery Charge",
          amount: "1400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "224920",
          deliveryTime: 16,
          minDeliveryTime: 16,
          maxDeliveryTime: 16,
          lastMileTravel: 0.30000001192092896,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
  
    // 3rd
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "550507",
        name: "Old School Cafe",
        uuid: "27d1426d-afe2-4f11-a70e-5c36cef59b81",
        city: "50",
        area: "Civil Lines",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "fe2f3082b777232315cf0fd9d6ff08f5",
        cuisines: [
          "North Indian",
          "Chinese",
          "Continental",
          "Burgers",
          "Thai",
          "Biryani",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 3.5,
        slugs: {
          restaurant: "old-school-cafe-civil-lines-civil-lines-2",
          city: "allahabad",
        },
        cityState: "50",
        address: "33/2/A, Stretchy Road, Civil Lines, Allahabad, 211001",
        locality: "Stretchy Road",
        parentId: 151344,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7278100~p=4~eid=00000189-3539-747c-07ff-165f00720436~srvts=1688815105148",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "550507",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 3.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    // 4th
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "612797",
        name: "Vadilal Ice Creams",
        uuid: "32f559c1-25df-4cc6-af76-ee3dbf9f6882",
        city: "50",
        area: "Rambagh",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "edf6aa61ed4cdfcda130897c5b3e5255",
        cuisines: ["Ice Cream"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        slaString: "15 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "vadilal-ice-cream-medical-chauraha-medical-chauraha",
          city: "allahabad",
        },
        cityState: "50",
        address:
          "SHREE SAI MARKETING-PRAYGRAJ-605/496-NAI BASTI,KYD GANJ,PRAYGRAJ,UTTARPRADESH",
        locality: "Kyd Ganj",
        parentId: 11745,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1400,
          message: "",
          title: "Delivery Charge",
          amount: "1400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "612797",
          deliveryTime: 15,
          minDeliveryTime: 15,
          maxDeliveryTime: 15,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    // 5th
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "714858",
        name: "Hyderabadi Biryani",
        uuid: "a18c2ff5-1de4-4a38-97ee-108a19204bdc",
        city: "50",
        area: "Civil Lines",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "b95fc0a3ce2ce7f9ff26363ec5b521dd",
        cuisines: ["Biryani", "North Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "hyderabadi-biryani-civil-lines-civil-lines-3",
          city: "allahabad",
        },
        cityState: "50",
        address: "Plot no 12 near vishal mega mart, civil line Allahabad 211001",
        locality: "Vishal Mega Mart",
        parentId: 15552,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7147810~p=7~eid=00000189-3539-747c-07ff-166000720752~srvts=1688815105148",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "714858",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 20,
        new: true,
      },
      subtype: "basic",
    },
  ];